#! /usr/bin/python3
import argparse

from src.main import main


# Dev hack to provide custom level list
parser = argparse.ArgumentParser()
parser.add_argument(
    '-l',
    '--levels',
    default='levels.txt',
    required=False
)
parser.add_argument(
    '--xmas',
    action='store_true',
    required=False
)

args = parser.parse_args()


main(args.levels, args.xmas)
