#! /usr/bin/python3
import argparse

from src.main import main


# Dev hack to provide custom level list
parser = argparse.ArgumentParser()
parser.add_argument(
    '-l',
    '--levels',
    default='levels.txt',
    required=False
)
parser.add_argument(
    '--xmas',
    action='store_true',
    required=False
)

parser.add_argument(
    '--windowed',
    action='store_true',
    required=False
)

parser.add_argument(
    '--player1',
    default='',
    required=False
)

parser.add_argument(
    '--player2',
    default='green',
    required=False
)

args = parser.parse_args()
colours = [args.player1, args.player2]


main(
    level_file=args.levels,
    xmas=args.xmas,
    colours=colours,
    fullsize=not args.windowed
)
